FROM centos:7.9.2009

RUN yum -y install wget 
RUN \
wget -O jdk.tar.gz "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz" && 
RUN yum -y install wget \
    && wget -O redis.tar.gz "https://download.redis.io/releases/redis-6.2.6.tar.gz" \
    && wget -O jdk.tar.gz "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz" \
    && wget -O maven.tar.gz "https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz" \
    && wget -O tomcat.tar.gz "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz" \
    && wget -O gradle.tar.gz "https://services.gradle.org/distributions/gradle-6.9.2-bin.zip" \
    && wget -O go.tar.gz "https://golang.google.cn/dl/go1.17.5.linux-amd64.tar.gz" \
    && wget -O Miniconda.sh "https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh"\
    && wget -O node.tar.xz "https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x64.tar.xz"